### ISSUE TITLE
Standards compliance

### ISSUE THREAD

**Issue by aaronbeekay** [BuckeyeCurrent/Sensor-Breakout-Board#1]
The following things need fixed before we can hit v1.0 on this board:

- [x] Remove junk files from repo (.s##, .b##) and add .gitignore
- [x] Add schematic, board top, board bottom PDFs
- [x] Add BOM
- [ ] Add Gerbers
- [x] Board name, revision, Current logo on silk

**Comment by cgreenbaum** [comment]
I resolved these issues. Please review the pull request again.
